# Generated by Django 2.0.2 on 2018-04-21 03:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('isPub', models.BooleanField(default=False, verbose_name='发布状态')),
                ('commentNum', models.IntegerField(default=0, verbose_name='评论数')),
                ('readNum', models.IntegerField(default=0, verbose_name='阅读数')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryName', models.CharField(max_length=128, verbose_name='分类')),
                ('categoryImg', models.ImageField(upload_to='categoryImg')),
                ('categoryId', models.IntegerField(db_column='分类ID', default=1, primary_key=True, serialize=False, verbose_name='分类ID')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='评论标题')),
                ('content', models.TextField(default='', verbose_name='评论内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagName', models.CharField(max_length=128, verbose_name='标签')),
                ('tagId', models.IntegerField(db_column='标签ID', default=1, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
