# Generated by Django 2.0.2 on 2018-04-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=128, verbose_name='类别')),
                ('categoryId', models.IntegerField(default=0, verbose_name='类别ID')),
            ],
        ),
    ]
