# Generated by Django 2.0.2 on 2018-04-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180418_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagId',
            field=models.IntegerField(db_column='tagId', default=1, primary_key=True, serialize=False),
        ),
    ]
