# Generated by Django 2.0.2 on 2018-04-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180418_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryId',
            field=models.IntegerField(db_column='类别ID', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagId',
            field=models.IntegerField(db_column='类别ID', default=1, primary_key=True, serialize=False),
        ),
    ]
