# Generated by Django 2.0.2 on 2018-04-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180418_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryId',
            field=models.IntegerField(db_column='类别ID', default=1, primary_key=True, serialize=False, verbose_name='类别ID'),
        ),
    ]
