# Generated by Django 2.0.2 on 2018-04-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZhysArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('img', models.CharField(max_length=200, verbose_name='图片地址')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ZhysHomeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('img', models.CharField(max_length=200, verbose_name='图片')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='zhysarticleinfo',
            name='home_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderManager.ZhysHomeInfo'),
        ),
    ]
